php:
    dockerfile: ./containers/php/Dockerfile
    build: ./
    links:
        - mysql
    expose:
        - 9000
    container_name: videoserver_php

nginx:
    dockerfile: Dockerfile
    build: ./containers/nginx
    ports:
        - 80:80
    environment:
        - NGINX_HOST=localhost
        - NGINX_PORT=80
    links:
        - mysql
        - php
        - rabbitmq
    container_name: videoserver_nginx
    volumes:
        - ./log:/etc/logs/nginx

mysql:
    image: mysql:latest
    container_name: videoserver_mysql
    ports:
        - 3306:3306
    expose:
        - 3306
    environment:
        MYSQL_DATABASE: video-server
        MYSQL_ROOT_PASSWORD: root

supervisor:
    dockerfile: Dockerfile
    build: ./containers/supervisor
    volumes:
        - ./log:/var/log/
    links:
        - rabbitmq
        - mysql
        - php
    container_name: videoserver_supervisor
    ports:
        - 9010:9010

rabbitmq:
    image: rabbitmq:management
    container_name: videoserver_rabbitmq
    ports:
        - 15672:15672
    expose:
        - 5672
