php:
    dockerfile: ./Dockerfile
    build: ./
    container_name: videoserver_php
    volumes:
        - ./:/var/www:rw

web:
    image: nginx:latest
    ports:
        - 80:80
    environment:
     - NGINX_HOST=localhost
     - NGINX_PORT=80
    links:
        - mysql
        - php
    container_name: videoserver_nginx
    volumes_from:
        - php:rw
    volumes:
        - ./log:/etc/logs/nginx
        # TODO: mount only nginx.conf file
        - ./config:/etc/nginx/conf.d

mysql:
    image: mysql:latest
    container_name: videoserver_mysql
    ports:
        - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: root
        MYSQL_PASSWORD: root
