mysql:
    image: mysql:latest
    container_name: videoserver_mysql
    ports:
        - 3306:3306
    expose:
        - 3306
    environment:
        MYSQL_DATABASE: video-server
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: root
        MYSQL_PASSWORD: root

php:
    dockerfile: ./containers/php/Dockerfile
    build: ./
    container_name: videoserver_php
    links:
        - mysql
    volumes:
        - ./:/var/www:rw

web:
    dockerfile: Dockerfile
    build: ./containers/nginx
    ports:
        - 80:80
    environment:
     - NGINX_HOST=localhost
     - NGINX_PORT=80
    links:
        - mysql
        - php
    container_name: videoserver_nginx
    volumes_from:
        - php:rw
    volumes:
        - ./log:/etc/logs/nginx
