# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: videofile, action: index }

video_file_create:
  url: /videofile/create
  class: sfRequestRoute
  options: { model: VideoFile, type: object }
  param: { module: videofile, action: create }
  requirements:
    sf_method: [post]

video_file_show:
  url: /videofile/show/:id
  class: sfRequestRoute
  options: { model: VideoFile, type: object }
  param: { module: videofile, action: show }
  requirements:
    sf_method: [get]

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
