propel:
  video_file:
    id:           ~
    type:         { type: integer }
    preview:      { type: varchar(255) }
    url:          { type: varchar(255) }
    title:        { type: varchar(255) }
    description:  { type: longvarchar }
    created_at:   ~
    updated_at:   ~