propel:
  video_file:
    id:           ~
    type:         { type: tinyint }
    dir:          { type: varchar(255) }
    filename:     { type: varchar(255) }
    duration:     { type: float }
    size:         { type: bigint }
    title:        { type: varchar(255) }
    description:  { type: longvarchar }
    state:        { type: tinyint, default: 0 }
    created_at:   ~
    updated_at:   ~

  video_thumb:
    video_file_id:  { type: integer, foreignTable: video_file, foreignReference: id }
    thumb_id:       { type: integer, foreignTable: thumb, foreignReference: id }

  thumb:
    id:           ~
    filename:     { type: varchar(255) }
    dir:          { type: varchar(255) }
